config/routes.rb
Rails.application.routes.draw do
  resources :events
  resources :nations
  resources :people
  root :to => "welcome#index"
  get "welcome/say_hello" => "welcome#say"
  get "welcome"           => "welcome#index"
  
end

app/models/attendee.rb
class Attendee < ActiveRecord::Base
	belongs_to :event # 單數
end

app/models/category.rb
class Category < ActiveRecord::Base
	has_many :events
end

app/models/event.rb
class Event < ActiveRecord::Base
	has_one :location
	belongs_to :category
	has_many :attendees, ->{ order("id DESC") }
	# has_many :attendees, ->{ where(["created_at > ?", Time.now - 7.day]).order("id DESC") }
	validates_presence_of :name
	
	# has_many :attendees, :dependent => :destroy
	# 可以設定當物件刪除時，也會順便刪除它的has_many物件：
	
	has_many :event_groupships
	has_many :groups, :through => :event_groupships
end

app/models/event_groupship.rb
class EventGroupship < ActiveRecord::Base
	belongs_to :event
	belongs_to :group
end

app/models/group.rb
class Group < ActiveRecord::Base
    has_many :event_groupships
    has_many :events, :through => :event_groupships
end

app/models/location.rb
class Location < ActiveRecord::Base
	belongs_to :event
end

app/models/nation.rb
class Nation < ActiveRecord::Base
end

app/models/person.rb
class Person < ActiveRecord::Base
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/events_controller.rb
class EventsController < ApplicationController
	before_action :set_event, :only => [ :show, :edit, :update, :destroy]
	def index
		@events = Event.page(params[:page]).per(5)

		respond_to do |format|
			format.html # index.html.erb
			format.xml { render :xml => @events.to_xml }
			format.json { render :json => @events.to_json }
			format.atom { @feed_title = "My event list" } # index.atom.builder
		end
	end

	def show
	  @event = Event.find(params[:id])
	  respond_to do |format|
	    format.html { @page_title = @event.name } # show.html.erb
	    format.xml # show.xml.builder
	    format.json { render :json => { id: @event.id, name: @event.name }.to_json }
	  end
	end

	def edit
	end

	def new
		@event = Event.new
	end

	def update
	  @event.update(event_params)
	  redirect_to event_url(@event)
	  flash[:notice] = "event was successfully update"
	end

	def create
	  @event = Event.new(event_params)
	  if @event.save
	    redirect_to :action => :index
	  else
	    render :action => :new
	  end
	  flash[:notice] = "event was successfully created"
	end

	def destroy
	  @event.destroy

	  redirect_to events_url
	  flash[:notice] = "event was successfully deleted"
	end

	private

	def event_params
		params.require(:event).permit(:name, :description)
	end

	def set_event
  @event = Event.find(params[:id])
	end
end

app/controllers/nations_controller.rb
class NationsController < ApplicationController
  before_action :set_nation, only: [:show, :edit, :update, :destroy]

  # GET /nations
  # GET /nations.json
  def index
    @nations = Nation.all
  end

  # GET /nations/1
  # GET /nations/1.json
  def show
  end

  # GET /nations/new
  def new
    @nation = Nation.new
  end

  # GET /nations/1/edit
  def edit
  end

  # POST /nations
  # POST /nations.json
  def create
    @nation = Nation.new(nation_params)

    respond_to do |format|
      if @nation.save
        format.html { redirect_to @nation, notice: 'Nation was successfully created.' }
        format.json { render :show, status: :created, location: @nation }
      else
        format.html { render :new }
        format.json { render json: @nation.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /nations/1
  # PATCH/PUT /nations/1.json
  def update
    respond_to do |format|
      if @nation.update(nation_params)
        format.html { redirect_to @nation, notice: 'Nation was successfully updated.' }
        format.json { render :show, status: :ok, location: @nation }
      else
        format.html { render :edit }
        format.json { render json: @nation.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /nations/1
  # DELETE /nations/1.json
  def destroy
    @nation.destroy
    respond_to do |format|
      format.html { redirect_to nations_url, notice: 'Nation was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_nation
      @nation = Nation.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def nation_params
      params.require(:nation).permit(:name, :size, :population)
    end
end

app/controllers/people_controller.rb
class PeopleController < ApplicationController
  before_action :set_person, only: [:show, :edit, :update, :destroy]

  # GET /people
  # GET /people.json
  def index
    @people = Person.all
  end

  # GET /people/1
  # GET /people/1.json
  def show
  end

  # GET /people/new
  def new
    @person = Person.new
  end

  # GET /people/1/edit
  def edit
  end

  # POST /people
  # POST /people.json
  def create
    @person = Person.new(person_params)

    respond_to do |format|
      if @person.save
        format.html { redirect_to @person, notice: 'Person was successfully created.' }
        format.json { render :show, status: :created, location: @person }
      else
        format.html { render :new }
        format.json { render json: @person.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /people/1
  # PATCH/PUT /people/1.json
  def update
    respond_to do |format|
      if @person.update(person_params)
        format.html { redirect_to @person, notice: 'Person was successfully updated.' }
        format.json { render :show, status: :ok, location: @person }
      else
        format.html { render :edit }
        format.json { render json: @person.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /people/1
  # DELETE /people/1.json
  def destroy
    @person.destroy
    respond_to do |format|
      format.html { redirect_to people_url, notice: 'Person was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_person
      @person = Person.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def person_params
      params.require(:person).permit(:name, :bio, :birthday)
    end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
	def index
	end
	def say
	end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/events_helper.rb
module EventsHelper
end

app/helpers/nations_helper.rb
module NationsHelper
end

app/helpers/people_helper.rb
module PeopleHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/events/_form.html.erb
<%= f.label :name, "Name" %>
<%= f.text_field :name %>

<%= f.label :description, "Description" %>
<%= f.text_area :description %>
<% if @event.errors.any? %>
      <ul>
      <% @event.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
<% end %>

app/views/events/edit.html.erb
<%= form_for @event do |f| %>
  <%= render :partial => 'form', :locals => { :f => f } %>
  <%= f.submit "Update" %>
<% end %>

app/views/events/index.html.erb
<% @events.each do |event| %>
  <li>
    <%= link_to event.name, event_path(event) %>
    <%= link_to " (XML)", event_path(event, :format => :xml) %>
    <%= link_to " (JSON)", event_path(event, :format => :json) %>
    <%= link_to 'edit', edit_event_path(event) %>
    <%= button_to 'delete', event_path(event), :method => :delete, :data => { :confirm => "Are you sure?" } %>
  </li>
<% end %>
</ul>

<%= link_to 'new event', new_event_path %>
<%= link_to "Atom feed", events_path(:format => :atom) %>
<%= paginate @events %>

app/views/events/new.html.erb
<%= form_for @event, :url => events_path do |f| %>
  <%= render :partial => 'form', :locals => { :f => f } %>
  <%= f.submit "Create" %>
<% end %>

app/views/events/show.html.erb
<%= @event.name %>
<%= simple_format(@event.description) %>

<p><%= link_to 'Back to index', events_path %></p>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title><%= @page_title || "Event application" %></title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
<p style="color: green"><%= flash[:notice] %></p>
<p style="color: red"><%= flash[:alert] %></p>

<%= yield %>

</body>
</html>

app/views/nations/_form.html.erb
<%= form_for(@nation) do |f| %>
  <% if @nation.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@nation.errors.count, "error") %> prohibited this nation from being saved:</h2>

      <ul>
      <% @nation.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :size %><br>
    <%= f.text_field :size %>
  </div>
  <div class="field">
    <%= f.label :population %><br>
    <%= f.number_field :population %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/nations/edit.html.erb
<h1>Editing Nation</h1>

<%= render 'form' %>

<%= link_to 'Show', @nation %> |
<%= link_to 'Back', nations_path %>

app/views/nations/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing Nations</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Size</th>
      <th>Population</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @nations.each do |nation| %>
      <tr>
        <td><%= nation.name %></td>
        <td><%= nation.size %></td>
        <td><%= nation.population %></td>
        <td><%= link_to 'Show', nation %></td>
        <td><%= link_to 'Edit', edit_nation_path(nation) %></td>
        <td><%= link_to 'Destroy', nation, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Nation', new_nation_path %>

app/views/nations/new.html.erb
<h1>New Nation</h1>

<%= render 'form' %>

<%= link_to 'Back', nations_path %>

app/views/nations/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @nation.name %>
</p>

<p>
  <strong>Size:</strong>
  <%= @nation.size %>
</p>

<p>
  <strong>Population:</strong>
  <%= @nation.population %>
</p>

<%= link_to 'Edit', edit_nation_path(@nation) %> |
<%= link_to 'Back', nations_path %>

app/views/people/_form.html.erb
<%= form_for(@person) do |f| %>
  <% if @person.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@person.errors.count, "error") %> prohibited this person from being saved:</h2>

      <ul>
      <% @person.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :bio %><br>
    <%= f.text_area :bio %>
  </div>
  <div class="field">
    <%= f.label :birthday %><br>
    <%= f.date_select :birthday %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/people/edit.html.erb
<h1>Editing Person</h1>

<%= render 'form' %>

<%= link_to 'Show', @person %> |
<%= link_to 'Back', people_path %>

app/views/people/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Listing People</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Bio</th>
      <th>Birthday</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @people.each do |person| %>
      <tr>
        <td><%= person.name %></td>
        <td><%= person.bio %></td>
        <td><%= person.birthday %></td>
        <td><%= link_to 'Show', person %></td>
        <td><%= link_to 'Edit', edit_person_path(person) %></td>
        <td><%= link_to 'Destroy', person, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Person', new_person_path %>

app/views/people/new.html.erb
<h1>New Person</h1>

<%= render 'form' %>

<%= link_to 'Back', people_path %>

app/views/people/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @person.name %>
</p>

<p>
  <strong>Bio:</strong>
  <%= @person.bio %>
</p>

<p>
  <strong>Birthday:</strong>
  <%= @person.birthday %>
</p>

<%= link_to 'Edit', edit_person_path(@person) %> |
<%= link_to 'Back', people_path %>

app/views/welcome/index.html.erb
<p> Hola! It's <%= Time.now %></p>
<p><%= link_to 'Hello!', welcome_say_hello_path %></p>

app/views/welcome/say.html.erb
<h1>Hello, It's Huaiyu Lin's website!</h1>
<p><%= link_to 'Home', root_path %></p>